### ISSUE TITLE
V10

### ISSUE THREAD

**Issue by docphil30** [DjLeChuck/foundryvtt-system-channel-fear#1]
No compatibilty V10, impossible to open pre-generated character

**Comment by DjLeChuck** [comment]
Fixed with 5db62872165e98331132ebf658e0695894a457d3

New version `0.1.3` up.

Thank you! 🙂

**Comment by docphil30** [comment]
Non merci à vous !

Envoyé à partir de Courrier pour Windows

De : Vivien DE BONA
Envoyé le :jeudi 6 octobre 2022 22:09
À : DjLeChuck/foundryvtt-system-channel-fear
Cc : docphil30; Author
Objet :Re: [DjLeChuck/foundryvtt-system-channel-fear] V10 (Issue #1)

Fixed with 5db6287
New version 0.1.3 up.
Thank you! 🙂
