### ISSUE TITLE
Souci lors de la gestion des relances lors d'un jet effectué depuis une arme

### ISSUE THREAD

**Issue by JhaelenTerear** [DjLeChuck/foundryvtt-system-channel-fear#10]
Hello,

Soit j'ai pas compris comment c'est censé fonctionner, soit il y a un souci lorsqu'on utilise directement une arme pour faire un jet : les relances ne semblent pas prises en compte.

Exemple (avec le prétiré Archi) :
- Je clique sur son arme Colt 45 (en éditant, relance bien indiquée à 2)
- Je choisis une difficulté de 4
- Dans le message du jet dans le chat, pas de possibilité de déclencher une relance (comme on peut le voir lors d'un test effectué depuis une spécialité)

![image](https://github.com/DjLeChuck/foundryvtt-system-channel-fear/assets/58259514/8d7aba91-a25d-4e40-a617-33a9f87df09f)
![image](https://github.com/DjLeChuck/foundryvtt-system-channel-fear/assets/58259514/2e150a65-7585-40ff-965f-4f7d52d7945b)

**Comment by DjLeChuck** [comment]
Bonsoir !

La relance sur les armes concerne les dégâts et non le jet d’attaque. :)

Extrait des règles :

> À la manière des Spécialités, certaines sources de dégâts permettent de relancer un ou plusieurs dés qui n’auraient pas affiché une réussite, assurant ainsi presque à coup sûr un nombre de dégâts minimum. Le nombre de dés pouvant être relancé est indiqué entre parenthèses pour les sources de dégâts qui bénéficient de cette spécificité.

Lorsqu’on veut utiliser une arme, il faut cliquer dessus pour faire d’abord son lancer d’aptitude, puis si ce dernier est réussi il y aura de proposé son jet de dégâts avec prise en compte des relances.

**Comment by JhaelenTerear** [comment]
Oui, je me suis mal exprimé. Effectivement, il y a une relance pour les
dégâts. Mais, dans le cas de la spécialité Armes à feu de Viser que possède
Archie, il devrait aussi y avoir une relance sur le jet d'aptitude aussi,
non ?

Le ven. 11 août 2023 à 18:41, Vivien DE BONA ***@***.***> a
écrit :

**Comment by DjLeChuck** [comment]
Je viens de me repencher sur les règles, cela faisait longtemps, et tu as parfaitement raison : si une spécialité utilise l’aptitude demandée alors on a l’air de pouvoir utiliser les relances liées.

Le système ne permet pas de gérer ce genre de cas en effet. Je n’utilise plus le système, je le maintiens seulement pour les montées de version, donc je pense que le plus simple est de gérer ces cas « à la main ».

**Comment by JhaelenTerear** [comment]
Ok ça marche, effectivement, c'est possible de gérer ça à la main.

**Comment by DjLeChuck** [comment]
Merci quand même pour ta rémontée !

Bonne soirée et bon jeu. :)
