### ISSUE TITLE
An unexpected error occured...11.2.0.zip:Not Found

### ISSUE THREAD

**Issue by madprocessor** [DjLeChuck/foundryvtt-system-channel-fear#15]
![2024-03-22_19-29-04](https://github.com/DjLeChuck/foundryvtt-system-channel-fear/assets/4673336/68195697-70f5-466e-bff7-a86ede0512ce)
Hi,
During system updates, it is launched but results in the error message: An unexpected error occurred when downloading file https://github.com/DjLeChuck/foundryvtt-system-channel-fear/archive/11.2. 0.zip:Not Found
Thks,

**Comment by DjLeChuck** [comment]
Woops indeed, sorry!

It should be fix now!
