### ISSUE TITLE
Having issues updating

### ISSUE THREAD

**Issue by trombonecot** [DjLeChuck/foundryvtt-system-channel-fear#7]
Hi!

Don't know if it's the proper place to raise the hand here, but I'm having trouble installing channel feat system. No matter what I do, install from marketplace, update it, or from the json, I always get version 0.0.7. I wanted to install the last one to get the catalan translation but no luck :(

Maybe there is some configuration json pointing to 0.0.7 by mistake or something? 

<img width="941" alt="Captura de pantalla 2022-12-29 a las 8 46 36" src="https://user-images.githubusercontent.com/2720788/209919959-9834b5d9-1b0b-465f-b47d-d3525bb90e3b.png">

**Comment by DjLeChuck** [comment]
Hi,

The `0.0.7` is the last version for Foundry v9. If you want to update the system, you must use Foundry v10.

If you're already using it, juste uninstall the system and install it again.

**Comment by trombonecot** [comment]
Thanks and sorry, I had to update and uninstall a couple of times until it worked. But I'm with the catalan version now. Thanks!

**Comment by DjLeChuck** [comment]
You're welcome! 👍🏻
