### ISSUE TITLE
Manifest for 11.1.0 is empty

### ISSUE THREAD

**Issue by Onioninblack** [DjLeChuck/foundryvtt-system-channel-fear#8]
I have instaled 11.0.0

**Comment by DjLeChuck** [comment]
Woops, you’re right! Should be OK now. :)

**Comment by Onioninblack** [comment]
I love this game thanks a lot for your work,

**Comment by DjLeChuck** [comment]
You’re welcome!
It’s a really cool game, yes. 😄
